"""Central runtime configuration.

Keep tunable runtime values grouped by subsystem and prefixed with their owner
module's name. See CONFIGURATION.md for the layout and conditional settings.
"""
import os
from datetime import time as dt_time

import pytz

# System-wide defaults and execution mode.
SYSCNFGPXY_TICKER = "^NSEI"
SYSCNFGPXY_TIMEZONE = pytz.timezone("Asia/Kolkata")
SYSMODEPXY_RUN_MODE = os.environ.get(
    "RUNMODE", "PRD"
)  # PRD: live engine, CHK: mock engine, SIM: historical replay.
if SYSMODEPXY_RUN_MODE not in {"PRD", "CHK", "SIM"}:
    raise ValueError("RUNMODE must be one of 'PRD', 'CHK', or 'SIM'.")

# Engine launchers and scheduling.
# Shared trading schedule. Keep distinct close windows explicit: the supervisor,
# execution loop, and point replay intentionally stop at different times.
SYSCNFGPXY_EXCHANGE_OPEN = dt_time(9, 15)
SYSCNFGPXY_PREOPEN_START = dt_time(9, 14)
SYSCNFGPXY_MARKET_OPEN = dt_time(9, 16)
SYSCNFGPXY_ENGINE_CLOSE = dt_time(15, 45)
SYSCNFGPXY_TRADING_PIPE_CLOSE = dt_time(15, 29)
SYSCNFGPXY_TRADING_DAY_END = dt_time(15, 30)
SYSCNFGPXY_AVERAGING_START = dt_time(9, 17)
SYSCNFGPXY_ENTRY_CUTOFF = dt_time(15, 10)
SYSCNFGPXY_SQUAREOFF_START = dt_time(15, 11)
SYSCNFGPXY_SQUAREOFF_ALL_START = dt_time(15, 14)
SYSCNFGPXY_SQUAREOFF_END = dt_time(15, 50)
if not (
    SYSCNFGPXY_EXCHANGE_OPEN <= SYSCNFGPXY_MARKET_OPEN < SYSCNFGPXY_ENGINE_CLOSE
    and SYSCNFGPXY_PREOPEN_START <= SYSCNFGPXY_MARKET_OPEN
    and SYSCNFGPXY_ENTRY_CUTOFF < SYSCNFGPXY_SQUAREOFF_START
    and SYSCNFGPXY_SQUAREOFF_START < SYSCNFGPXY_SQUAREOFF_ALL_START
    and SYSCNFGPXY_SQUAREOFF_ALL_START < SYSCNFGPXY_SQUAREOFF_END
):
    raise ValueError("Shared market-hours settings are not in chronological order.")

SYSEXEPXY_MARKET_OPEN = SYSCNFGPXY_MARKET_OPEN
SYSEXEPXY_MARKET_CLOSE = SYSCNFGPXY_ENGINE_CLOSE
SYSEXEPXY_SUPERVISOR_INTERVAL_SECONDS = 1
EXEPXYPXY_MARKET_OPEN = SYSCNFGPXY_MARKET_OPEN
EXEPXYPXY_MARKET_CLOSE = SYSCNFGPXY_TRADING_PIPE_CLOSE
EXEPXYPXY_PIPE_TIMEOUT_SECONDS = 60
EXEPXYPXY_SUB_ITERATIONS = 30
EXEPXYPXY_IDLE_PAUSE_SECONDS = 6
EXEPXYPXY_IDLE_POLL_SECONDS = 60
SYSCNFGPXY_ACTION_COOLDOWN_SECONDS = 6

# Data ingestion, chart generation, and signal calculation.
SYSDTAFPXY_FORCE_NIFTY_FUT = False
SYSDTAFPXY_DEFAULT_INTERVAL = "1m"
SYSDTAFPXY_DEFAULT_TARGET_ROWS = 60
SYSSMAPXY_VARIANT = "TSMA"
if SYSSMAPXY_VARIANT not in {"SMA", "TSMA"}:
    raise ValueError("SYSSMAPXY_VARIANT must be SMA or TSMA.")
SYSSTRNDPXY_CHART_TARGET_ROWS = 110
if SYSSTRNDPXY_CHART_TARGET_ROWS < 110:
    raise ValueError("SYSSTRNDPXY_CHART_TARGET_ROWS must be at least 110.")
SYSPLCHRTPXY_OHLC_MODE = 1
SYSPLCHRTPXY_SMA_WINDOW = 4
SYSPLCHRTPXY_FETCH_INTERVAL = "1m"
SYSPLCHRTPXY_TARGET_ROWS = 60
if SYSPLCHRTPXY_OHLC_MODE not in {1, 2, 3, 4, 5, 6}:
    raise ValueError("SYSPLCHRTPXY_OHLC_MODE must be between 1 and 6.")
SYSDTHAPXY_INCLUDE_RUNNING_CANDLE = "YES"
if SYSDTHAPXY_INCLUDE_RUNNING_CANDLE not in {"YES", "NO"}:
    raise ValueError("SYSDTHAPXY_INCLUDE_RUNNING_CANDLE must be YES or NO.")

SYSSTRNDPXY_ST1_ATR_PERIOD = 10
SYSSTRNDPXY_ST1_FACTOR = 3.0

SYSDTSTPXY_ST1_PERIOD = 3.0
SYSDTSTPXY_ST1_FACTOR = 1.4

# BOS morning recognition ends at 10:10; its opening boundary uses the shared
# exchange open above.
SYSBBOSPXY_MORNING_SESSION_END = dt_time(10, 10)
SYSSADXPXY_USE_TSMA = True
SYSSADXPXY_MA_PERIOD = 50
SYSSADXPXY_SUPERTREND_PERIOD = 10
SYSSADXPXY_SUPERTREND_FACTOR = 3.0
SYSSADXPXY_FORCE_BASE = 1.0
SYSSADXPXY_FORCE_BOOST = 1.2
SYSSADXPXY_FORCE_NEUTRAL = 1.1
SYSMKTPXY_DEBUG_ENABLED = True
SYSRIGPXY_DEBUG_ENABLED = False

SYSKATRPXY_ATR_MODE = 2
if SYSKATRPXY_ATR_MODE not in {1, 2, 3}:
    raise ValueError("SYSKATRPXY_ATR_MODE must be 1 (static), 2 (true ATR), or 3 (dynamic).")
SYSKATRPXY_ATR_STATIC_VALUE = 7
SYSKATRPXY_TRUE_ATR_PERIOD = 14
SYSKATRPXY_TRUE_ATR_MAX = 10.0
SYSKATRPXY_TRUE_ATR_MIN_ROWS = 1
SYSKATRPXY_TRUE_ATR_FALLBACK_VALUE = 4.0
SYSKATRPXY_DEPTH_ATR_MINIMUM = 5

SYSPWERPXY_LOOKBACK_PERIOD = 5
SYSDPTPXY_LAST_N = 21

# Entry signal interpretation and averaging.
EXEAGTPXY_SYSTEM_A_BASE_THRESHOLD = 8.2
EXEAGTPXY_SYSTEM_B_BASE_THRESHOLD = 1.4
EXEAGTPXY_ABS_CAP = 77.0
EXEAGTPXY_FORCE_DEFAULT = 1.2

EXEAMSPXY_MAX_INVESTMENT = 25000.0
EXEAMSPXY_MAX_LGT_LOSS = 77.0
EXEAMSPXY_ORDER_EXCHANGE_SEGMENT = "nse_fo"
EXEAMSPXY_ORDER_PRODUCT = "NRML"
EXEAMSPXY_ORDER_PRICE = "0"
EXEAMSPXY_ORDER_TYPE = "MKT"
EXEAMSPXY_ORDER_VALIDITY = "DAY"
EXEAMSPXY_ORDER_TRANSACTION_TYPE = "B"
EXEAMSPXY_ORDER_AMO = "NO"

# Entry pipeline.
EXEENTRPXY_DEBUG_ENABLED = False
EXEENTRPXY_PREOPEN_START = SYSCNFGPXY_PREOPEN_START
EXEENTRPXY_PREOPEN_END = SYSCNFGPXY_MARKET_OPEN
EXEENTRPXY_ENTRY_CUTOFF = SYSCNFGPXY_ENTRY_CUTOFF
EXEENTRPXY_SQUAREOFF_END = SYSCNFGPXY_SQUAREOFF_END

# Manual force-order command.
EXEFORCEPXY_DEBUG_ENABLED = True
EXEFORCEPXY_NIFTY_LOT_SIZE = 65
EXEFORCEPXY_ORDER_EXCHANGE_SEGMENT = "nse_fo"
EXEFORCEPXY_ORDER_PRODUCT = "NRML"
EXEFORCEPXY_ORDER_PRICE = "0"
EXEFORCEPXY_ORDER_TYPE = "MKT"
EXEFORCEPXY_ORDER_VALIDITY = "DAY"
EXEFORCEPXY_ORDER_TRANSACTION_TYPE = "B"
EXEFORCEPXY_ORDER_AMO = "NO"

# Averaging and order-data pipelines.
EXEAVXPXY_USE_OVERALL_LOSS = True
EXEAVXPXY_REBUY_ENABLED = True
EXEAVXPXY_MARKET_START = SYSCNFGPXY_AVERAGING_START
EXEAVXPXY_MARKET_END = SYSCNFGPXY_ENTRY_CUTOFF
EXEAVGPXY_IDLE_EXIT_MODE = "one"
EXEOMSPXY_DEBUG_ENABLED = False

# Target and loss calculations.
EXETGTPXY_EXIT_KEY_COLUMN = "exit"
EXETGTPXY_ALIGNED_PCT = 77.0
EXETGTPXY_TGT_PCT_NOT_ALIGNED = 1.4

EXEDYNPXY_DECAY_RATE_PER_MIN = 0.0001
EXEDYNPXY_PNL_THRESHOLD = 0.0

# Option-symbol selection.
EXEOTMPXY_STRIKE_MODE = "ATM"  # "ATM", "OTMFIX", or "OTMDYN"; applies to every option buy.
EXEOTMPXY_FIXED_DISTANCE = 100
EXEOTMPXY_DYNAMIC_WEEKDAY_DISTANCES = (200, 150, 100, 50, 0)  # Monday through Friday.

RUNNIFTYPXY_STRIKE_STEP = 50
RUNNIFTYPXY_ATM_BUFFER = 0
RUNNIFTYPXY_HOLIDAYS = (
    "26-Jan-2026", "06-Mar-2026", "20-Mar-2026", "31-Mar-2026",
    "03-Apr-2026", "14-Apr-2026", "01-May-2026", "15-Aug-2026",
    "02-Oct-2026", "21-Oct-2026", "06-Nov-2026", "24-Nov-2026",
    "25-Dec-2026",
)

# Stop-loss, counter-leg, regular exit, and square-off behavior.
EXESLPXY_FIXED_SL_BUFFER = 10.0
EXESLPXY_MIN_PRICE = 2.0

EXECBUYPXY_ACTION = "YES"
EXECBUYPXY_DEBUG_ENABLED = False
EXECBUYPXY_CUTOFF = SYSCNFGPXY_ENTRY_CUTOFF
EXECBUYPXY_LOSS_TRIGGER_PCT = 1.4
EXECBUYPXY_SCRIPTS = {
    "CE": "pxybuype",
    "PE": "pxybuyce",
}
EXECBUYPXY_MAX_PER_DAY = 0  # Unlimited counter-buy when opposite side empty
EXECBUYPXY_LOCK_KEEP_SECS = 600

EXEEXITPXY_PNL_EXIT_MIN = 140
EXEEXITPXY_DEBUG_ENABLED = False
EXEEXITPXY_EXIT_LOCK_KEEP_SECS = 600
PASTRSK = "YES"
if PASTRSK not in {"YES", "NO"}:
    raise ValueError("PASTRSK must be YES or NO.")
EXEEXITPXY_DEPTH_EXIT_THRESHOLD = 6
if EXEEXITPXY_DEPTH_EXIT_THRESHOLD < 0:
    raise ValueError("EXEEXITPXY_DEPTH_EXIT_THRESHOLD must be non-negative.")
EXEEXITPXY_PASTRSK_LOSS_TRIGGER_PCT = 14.0
if not 0 <= EXEEXITPXY_PASTRSK_LOSS_TRIGGER_PCT <= 100:
    raise ValueError("EXEEXITPXY_PASTRSK_LOSS_TRIGGER_PCT must be between 0 and 100.")
EXEEXITPXY_SQUAREOFF_SCRIPT = "exesqrpxy.py"
EXEEXITPXY_SQOFF_START = SYSCNFGPXY_SQUAREOFF_START
EXEEXITPXY_SQOFF_ALL_START = SYSCNFGPXY_SQUAREOFF_ALL_START
EXEEXITPXY_SQOFF_END = SYSCNFGPXY_SQUAREOFF_END
EXEEXITPXY_SQUAREOFF_TIMEOUT_SECS = 120
EXEEXITPXY_SQOFF_MIN_GAP_SECS = 6
EXEEXITPXY_SYSDUMP_SCRIPT = "sysddmppxy.py"
EXEEXITPXY_ORDER_EXCHANGE_SEGMENT = "nse_fo"
EXEEXITPXY_ORDER_PRODUCT = "NRML"
EXEEXITPXY_ORDER_PRICE = "0"
EXEEXITPXY_ORDER_TYPE = "MKT"
EXEEXITPXY_ORDER_VALIDITY = "DAY"
EXEEXITPXY_ORDER_TRANSACTION_TYPE = "S"
EXEEXITPXY_ORDER_AMO = "NO"

EXESQRPXY_EXIT_ALL_AFTER = dt_time(15, 25)
EXESQRPXY_POST_EXIT_COOLDOWN_SECONDS = 6

# Portfolio risk ledger. Keep related thresholds together; the control switch
# gates the activation-time setting below.
RUNEXMTPXY_BRICK_SIZE = 50.0
RUNEXMTPXY_INITIAL_LOSS_FLOOR = -2000.0
RUNEXMTPXY_TARGET_PER_ACTIVE_RUNG = 1000.0
RUNEXMTPXY_PEAK_MULTIPLIER = 2.0  # Stop = initial floor + peak × multiplier.

RUNEXIOPXY_READ_ATTEMPTS = 3
RUNEXIOPXY_READ_RETRY_DELAY = 0.3
RUNEXIOPXY_WRITE_RETRIES = 2
RUNEXIOPXY_WRITE_RETRY_DELAY_SECONDS = 0.2

RUNEXACPXY_BREACH_TICKS_REQUIRED = 3
RUNEXACPXY_TICK_MIN_GAP_SECONDS = 10
RUNEXACPXY_LEDGER_BASIS_GUARD = True
RUNEXACPXY_STOP_SQUAREOFF_ENABLED = False
RUNEXACPXY_TARGET_SQUAREOFF_ENABLED = True
RUNEXACPXY_VIEW_ONLY_ENV = "PXY_VIEW_ONLY"
RUNEXACPXY_CNTRLRSKBAR = "YES"
if RUNEXACPXY_CNTRLRSKBAR not in {"YES", "NO"}:
    raise ValueError("RUNEXACPXY_CNTRLRSKBAR must be 'YES' or 'NO'.")
RUNEXACPXY_CNTRLRSKBAR_ACTIVATION_TIME = (
    dt_time(13, 15) if RUNEXACPXY_CNTRLRSKBAR == "YES" else None
)

RUNEXACPXY_DEBUG_ENABLED = False

# Risk-ledger liquidation support and order-ledger filtering.
RUNEXLQDPXY_FLAT_CONFIRM_TIMEOUT_SECONDS = 10.0
RUNEXLQDPXY_FLAT_CONFIRM_POLL_SECONDS = 2.0
RUNEXLQDPXY_SQUAREOFF_TIMEOUT_SECONDS = 120

RUNLILOPXY_DEFAULT_FILTER_TIME = SYSCNFGPXY_MARKET_OPEN.strftime("%H:%M:%S")

# Test replay uses the same production session schedule by default.
TSTPOINTBTPXY_MARKET_OPEN = SYSCNFGPXY_MARKET_OPEN
TSTPOINTBTPXY_MARKET_CLOSE = SYSCNFGPXY_TRADING_PIPE_CLOSE
TSTPOINTBTPXY_PREOPEN_START = SYSCNFGPXY_PREOPEN_START
TSTPOINTBTPXY_PREOPEN_END = SYSCNFGPXY_MARKET_OPEN
TSTPOINTBTPXY_ENTRY_CUTOFF = SYSCNFGPXY_ENTRY_CUTOFF
TSTPOINTBTPXY_SQUAREOFF_END = SYSCNFGPXY_SQUAREOFF_END
TSTPOINTBTPXY_FORCE_EXIT_TIME = SYSCNFGPXY_SQUAREOFF_ALL_START
TSTPOINTBTPXY_TRADING_DAY_START = SYSCNFGPXY_EXCHANGE_OPEN
TSTPOINTBTPXY_TRADING_DAY_END = SYSCNFGPXY_TRADING_DAY_END

# ---------------- SYSTEM SELF TEST ----------------
if __name__ == "__main__":
    print("=== CONFIGURATION FILE VERIFICATION ===")
    print(f"TARGET TICKER  : {SYSCNFGPXY_TICKER}")
    print(f"SYSTEM TIMEZONE: {SYSCNFGPXY_TIMEZONE}")
