# syscnfgpxy.py
"""
Executes exactly 6 structural, isolated OHLC mathematical transformations:
Mode 0: Hyper-Sensitive Modified Close Candles (Green Close=(High+Close)/2, Red Close=(Low+Close)/2)
Mode 1: Raw Candles
Mode 2: Mid-Body (OC/2) Pure Math Candles
Mode 3: Full Range (OHLC/4) Pure Math Candles
Mode 4: Standard Heikin-Ashi Candles
Mode 5: Master Ensemble Average of Modes 0, 1, 2, 3, and 4 (Divided by 5)
"""


from datetime import time as dt_time

import pytz

# ---------------- LOCAL SYSTEM CONFIGURATION ----------------
# -----------------------------------------------------------------------------
# Shared strategy and execution configuration.
# Name each value after its owning module: <MODULE>_<PARAMETER>.
# Keep credentials, presentation-only values, and file-system paths out of this
# module; credentials belong in the existing secret/environment configuration.
# -----------------------------------------------------------------------------
SYSCNFGPXY_TICKER = "^NSEI"
SYSCNFGPXY_TIMEZONE = pytz.timezone("Asia/Kolkata")
RUNMODE = "CHK"  # PRD: live engine, CHK: mock engine, SIM: historical replay.
if RUNMODE not in {"PRD", "CHK", "SIM"}:
    raise ValueError("RUNMODE must be one of 'PRD', 'CHK', or 'SIM'.")

SYSDTAFPXY_TIMEZONE = "Asia/Kolkata"
SYSDTAFPXY_SELECTED_MODE = "00"
SYSDTAFPXY_FORCE_NIFTY_FUT = False
SYSDTAFPXY_DEFAULT_INTERVAL = "1m"
SYSDTAFPXY_DEFAULT_TARGET_ROWS = 60
SYSDTAFPXY_TRANSFORM_ATR_PERIOD = 14
SYSDTAFPXY_FIXED_BRICK_SIZE = 2.0

SYSPLCHRTPXY_OHLC_MODE = 1
SYSPLCHRTPXY_SMA_WINDOW = 4
SYSPLCHRTPXY_FETCH_INTERVAL = "1m"
SYSPLCHRTPXY_TARGET_ROWS = 60

SYSSTRNDPXY_VARIANT = "DUAL"
SYSSTRNDPXY_ST1_PERIOD = 1.4
SYSSTRNDPXY_ST1_FACTOR = 1.4
SYSSTRNDPXY_SMA_PERIOD = 50
SYSSTRNDPXY_COMBO_ST_PERIOD = 10
SYSSTRNDPXY_COMBO_ST_FACTOR = 3.0
SYSSTRNDPXY_COMBO_SMA_PERIOD = 50

SYSDTSTPXY_ST1_PERIOD = 3.0
SYSDTSTPXY_ST1_FACTOR = 1.4
SYSDTSTPXY_ST2_PERIOD = 3.0
SYSDTSTPXY_ST2_FACTOR = 1.4

SYSSADXPXY_USE_TSMA = True
SYSSADXPXY_MA_PERIOD = 50
SYSSADXPXY_SUPERTREND_PERIOD = 10
SYSSADXPXY_SUPERTREND_FACTOR = 3.0

SYSKATRPXY_ATR_MODE = 3
SYSKATRPXY_ATR_STATIC_VALUE = 7
SYSKATRPXY_TRUE_ATR_PERIOD = 4
SYSKATRPXY_TRUE_ATR_MAX = 10.0
SYSKATRPXY_TRUE_ATR_MIN_ROWS = 5

SYSPWERPXY_LOOKBACK_PERIOD = 5
SYSDPTPXY_LAST_N = 21

EXEAGTPXY_SYSTEM_A_BASE_THRESHOLD = 8.2
EXEAGTPXY_SYSTEM_B_BASE_THRESHOLD = 1.4
EXEAGTPXY_ABS_CAP = 77.0
EXEAGTPXY_FORCE_DEFAULT = 1.2

EXEACGPXY_REBUY_ENABLED = True
EXEACGPXY_MAX_LAYERS = 5
EXEACGPXY_COOL_DOWN_SECONDS = 30
EXEACGPXY_MARKET_START = dt_time(9, 17)
EXEACGPXY_MARKET_END = dt_time(15, 10)

EXEAVXPXY_USE_OVERALL_LOSS = True

EXETGTPXY_EXIT_KEY_COLUMN = "exit"
EXETGTPXY_ATR_FLOOR = 1.4
EXETGTPXY_TGT_PCT_NOT_ALIGNED = 1.4

EXEDYNPXY_DECAY_RATE_PER_MIN = 0.0001
EXEDYNPXY_PNL_THRESHOLD = 0.0

EXEOTMPXY_DISTANCE_BY_WEEKDAY = {
    0: 250,
    1: 200,
    2: 150,
    3: 100,
    4: 50,
}
EXEOTMPXY_DEFAULT_DISTANCE = 100

RUNNIFTYPXY_STRIKE_STEP = 50
RUNNIFTYPXY_ATM_BUFFER = 0
RUNNIFTYPXY_HOLIDAYS = (
    "26-Jan-2026", "06-Mar-2026", "20-Mar-2026", "31-Mar-2026",
    "03-Apr-2026", "14-Apr-2026", "01-May-2026", "15-Aug-2026",
    "02-Oct-2026", "21-Oct-2026", "06-Nov-2026", "24-Nov-2026",
    "25-Dec-2026",
)

EXEENTRPXY_PREOPEN_START = dt_time(9, 14)
EXEENTRPXY_PREOPEN_END = dt_time(9, 16)
EXEENTRPXY_ENTRY_CUTOFF = dt_time(15, 10)
EXEENTRPXY_SQUAREOFF_END = dt_time(15, 50)

EXESLPXY_FIXED_SL_BUFFER = 10.0
EXESLPXY_MIN_PRICE = 2.0

EXECBUYPXY_ACTION = "YES"
EXECBUYPXY_LOCK_SECS = 6
EXECBUYPXY_CUTOFF = dt_time(15, 10)
EXECBUYPXY_EXIT_KEY_COLUMN = "exit"
EXECBUYPXY_SCRIPTS = {
    "CE": "pxybuype",
    "PE": "pxybuyce",
}
EXECBUYPXY_MAX_PER_DAY = 6
EXECBUYPXY_LOCK_KEEP_SECS = 600

EXEEXITPXY_PNL_EXIT_MIN = 140
EXEEXITPXY_EXIT_LOCK_SECS = 5
EXEEXITPXY_EXIT_LOCK_KEEP_SECS = 600
EXEEXITPXY_SQUAREOFF_SCRIPT = "exesqrpxy.py"
EXEEXITPXY_SQOFF_START = dt_time(15, 11)
EXEEXITPXY_SQOFF_ALL_START = dt_time(15, 14)
EXEEXITPXY_SQOFF_END = dt_time(15, 50)
EXEEXITPXY_SQUAREOFF_TIMEOUT_SECS = 120
EXEEXITPXY_SQOFF_MIN_GAP_SECS = 20
EXEEXITPXY_SYSDUMP_SCRIPT = "sysddmppxy.py"
EXEEXITPXY_ORDER_EXCHANGE_SEGMENT = "nse_fo"
EXEEXITPXY_ORDER_PRODUCT = "NRML"
EXEEXITPXY_ORDER_PRICE = "0"
EXEEXITPXY_ORDER_TYPE = "MKT"
EXEEXITPXY_ORDER_VALIDITY = "DAY"
EXEEXITPXY_ORDER_AMO = "NO"

EXESQRPXY_EXIT_ALL_AFTER = dt_time(15, 25)

RUNEXMTPXY_BRICK_SIZE = 50.0
RUNEXMTPXY_INITIAL_LOSS_FLOOR = -950.0
RUNEXMTPXY_TRAILING_DROP_GAP = 1400.0
RUNEXMTPXY_PEAK_GAP_FLOOR_PCT = 0.5
RUNEXMTPXY_TIGHTEN_PER_EXTRA_ROW = 0.05

RUNEXACPXY_RISK_ACTION = "YES"
RUNEXACPXY_BREACH_TICKS_REQUIRED = 3
RUNEXACPXY_TICK_MIN_GAP_SECONDS = 10
RUNEXACPXY_LEDGER_BASIS_GUARD = True
RUNEXACPXY_VIEW_ONLY_ENV = "PXY_VIEW_ONLY"

# Backwards-compatible shared names used by existing modules outside this
# strategy configuration migration.
TICKER = SYSCNFGPXY_TICKER
TIMEZONE = SYSCNFGPXY_TIMEZONE
PARAMS = {
    "ticker": SYSCNFGPXY_TICKER,  # Options: "^NSEI", "^NSEBANK", "BTC-USD", "GC=F", "GBPUSD=X", "^GSPC"
}

# ---------------- SYSTEM SELF TEST ----------------
if __name__ == "__main__":
    print("=== CONFIGURATION FILE VERIFICATION ===")
    print(f"TARGET TICKER  : {SYSCNFGPXY_TICKER}")
    print(f"SYSTEM TIMEZONE: {SYSCNFGPXY_TIMEZONE}")
