name: Mirror DEV to PRD

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DEV
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Mirror DEV to PRD
        env:
          TOKEN: ${{ secrets.TP }}
        run: |
          git remote add prd https://x-access-token:${TOKEN}@github.com/PreciseXceleratedYield-Pvt-Ltd/PRD.git
          git push --mirror prd
