name: TP_IMPORT

on:
  push:
    branches:
      - main

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DEV
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Force Sync to PRD
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: "https://github.com"
          token: ${{ secrets.TP_IMPORT }}
