name: TP_IMPORT

on:
  push:
    branches:
      - main

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DEV
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to PRD
        env:
          MY_SECRET_TOKEN: ${{ secrets.TP_IMPORT }}
        run: |
          git remote add target "https://x-access-token:${MY_SECRET_TOKEN}@://github.com"
          git push target main --force
