name: TP_IMPORT

on:
  push:
    branches:
      - main

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DEV
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to PRD
        run: |
          git remote add target https://x-access-token:${{ secrets.TP-IMPORT }}@://github.com
          git push target main --force
